---
openapi: 3.0.3
info:
  title: Rest Client Microservice
  description: Service-Two which consume Service-One
  version: "1.0"
paths:
  /api/rest-client:
    get:
      tags:
      - Rest Client Resource
      summary: Get Welcome Message
      description: 'Consume Message Microservice - getWelcomeMessage endpoint '
      responses:
        "200":
          description: OK
          content:
            application/json: {}
  /api/rest-client/create-message:
    post:
      tags:
      - Rest Client Resource
      summary: Create Message
      description: 'Consume Message Microservice - /create-message endpoint '
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            text/plain: {}
  /api/rest-client/throw-exception:
    post:
      tags:
      - Rest Client Resource
      summary: Throw Exception Message
      description: 'Consume Message Microservice - /throw-message endpoint '
      responses:
        "200":
          description: OK
          content:
            application/json: {}
components:
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
